# -*- coding: utf-8 -*-
"""Basics1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FT_asyE1HS7CVcDzIcG8lReSVFuG5D50

# Python Baiscs

VARIABLES
"""

age = 30
height = 6.1
name = "deevanshu"

print("age :", age)

"""## Lets make a Simple Calculator so that we can know better about variables

"""

num1 = float(input("enter the first number :"))
num2 = float(input("enter the second number:"))

num3 = num1 + num2
num3 = num1 - num2
num3 = num1 * num2
num3 = num1 / num2
num3 = num1 % num2

print(num3)

"""# Questions"""

## Question 1: Write a Python program to print "Hello, World!".

print("Hello World")

## Question 2: Write a Python program that takes a user input and prints it.
age = int(input("enter the age "))
print (age)

## Question 3: Write a Python program to check if a number is positive, negative, or zero.
Number = int(input("enter the Number "))
if(Number>0):
    print("Number is positive")
elif(Number<0):
    print("Number is negative")

from re import I
##Question 5: Write a Python program to calculate the factorial of a number.
fact = int(input("enter the number "))
for i in range(1,fact):
    fact = fact*i
print(fact)

