# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SxCzE-QYTUPm1u8TZoBtLPncwznS4X7f
"""

print("hello world")